# Module11~20
## 20200817-20200822

1. requests
1. uncurl
1. json
1. hashlib
1. hmac
1. bs4
1. selenium
1. webbrowser 
1. http
1. numpy  

---
## 2.11 requests
requests为基本网络交互工具
类似的库还有：`httplib` `urllib` `urllib2`
常用功能：`requests.get`, `requests.post`

In [1]:
import requests

headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
    }



doc = requests.get("https://book.douban.com/"
)

print(doc.status_code)


doc = requests.get("https://book.douban.com/",
    headers=headers
)

print(doc.text[0:1000])



418


<!DOCTYPE html>
<html lang="zh-CN" class="ua-windows ua-webkit book-new-nav">
  <head>
    <meta charset="utf-8">
    <meta name="google-site-verification" content="ok0wCgT20tBBgo9_zat2iAcimtN4Ftf5ccsh092Xeyw" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Expires" content="Sun, 6 Mar 2005 01:00:00 GMT">
    
  <meta http-equiv="mobile-agent" content="format=xhtml; url=https://m.douban.com/book/">
  <meta name="keywords" content="豆瓣读书,新书速递,畅销书,书评,书单"/>
  <meta name="description" content="记录你读过的、想读和正在读的书，顺便打分，添加标签及个人附注，写评论。根据你的口味，推荐适合的书给你。" />
  <meta name="verify-v1" content="EYARGSAVd5U+06FeTmxO8Mj28Fc/hM/9PqMfrlMo8YA=">
  <meta property="wb:webmaster" content="7c86191e898cd20d">
  <meta property="qc:admins" content="1520412177364752166375">

    <title>
    豆瓣读书
</title>
    <link rel="shortcut icon" href="https://img3.doubanio.com/favicon.ico"
      type="image/x-icon">
    <script s

In [2]:
import requests

doc = requests.get("https://baidu.com/",
    headers={
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
    }
)

print(doc.text[0:1000])


<!DOCTYPE html><!--STATUS OK-->


    <html><head><meta http-equiv="Content-Type" content="text/html;charset=utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta content="always" name="referrer"><meta name="theme-color" content="#2932e1"><meta name="description" content="全球最大的中文搜索引擎、致力于让网民更便捷地获取信息，找到所求。百度超过千亿的中文网页数据库，可以瞬间找到相关的搜索结果。"><link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /><link rel="search" type="application/opensearchdescription+xml" href="/content-search.xml" title="百度搜索" /><link rel="icon" sizes="any" mask href="//www.baidu.com/img/baidu_85beaf5496f291521eb75ba38eacbd87.svg"><link rel="dns-prefetch" href="//dss0.bdstatic.com"/><link rel="dns-prefetch" href="//dss1.bdstatic.com"/><link rel="dns-prefetch" href="//ss1.bdstatic.com"/><link rel="dns-prefetch" href="//sp0.baidu.com"/><link rel="dns-prefetch" href="//sp1.baidu.com"/><link rel="dns-prefetch" href="//sp2.baidu.com"/><title>百度一下，你就知道</title><style index="newi" type="text/css">

---
## 2.12 uncurl
uncurl 可以把curl命令转化为Python代码（requests模块）
常用功能：`uncurl.parse`

In [3]:
import uncurl


command = uncurl.parse("curl 'https://book.douban.com/' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' -H 'Cookie: bid=UwAOAuKwNuk; _vwo_uuid_v2=D5F84865EC2DDE95A868C7FE113BE5C00|15a26edbed437a65ea316806ffc7487c; gr_user_id=3822721a-0f72-4857-9eb8-07408745fdfd; gr_session_id_22c937bbd8ebd703f2d8e9445f7dfd03=a5a9f37e-ce09-4709-bba1-2ab02ff8bbc2; gr_cs1_a5a9f37e-ce09-4709-bba1-2ab02ff8bbc2=user_id%3A0; __utma=30149280.1171012025.1597718746.1597718746.1597718746.1; __utmc=30149280; __utmz=30149280.1597718746.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __utmt_douban=1; __utmb=30149280.1.10.1597718746; __utma=81379588.1954925261.1597718746.1597718746.1597718746.1; __utmc=81379588; __utmz=81379588.1597718746.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic; __utmt=1; __utmb=81379588.1.10.1597718746; gr_session_id_22c937bbd8ebd703f2d8e9445f7dfd03_a5a9f37e-ce09-4709-bba1-2ab02ff8bbc2=true; _pk_ref.100001.3ac3=%5B%22%22%2C%22%22%2C1597718749%2C%22https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DoHPx3751eMnMMm9iyzClcWNftUTdteNuLxAvJT44ercxLjTtvYRm_9CJ6prWVvlg%26wd%3D%26eqid%3Df3052594001d7586000000065f3b40c0%22%5D; _pk_id.100001.3ac3=efee8f6ae4fc8b5a.1597718749.1.1597718749.1597718749.; _pk_ses.100001.3ac3=*; __gads=ID=d58b0f34a8171fd4:T=1597718756:S=ALNI_Macl5IVxm1PB6riU1O3-jQnnauA9w' --compressed")
print(command)

requests.get("https://book.douban.com/",
    headers={
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
    },
    cookies={
        "__gads": "ID=d58b0f34a8171fd4:T=1597718756:S=ALNI_Macl5IVxm1PB6riU1O3-jQnnauA9w",
        "__utma": "81379588.1954925261.1597718746.1597718746.1597718746.1",
        "__utmb": "81379588.1.10.1597718746",
        "__utmc": "81379588",
        "__utmt": "1",
        "__utmt_douban": "1",
        "__utmz": "81379588.1597718746.1.1.utmcsr=baidu|utmccn=(organic)|utmcmd=organic",
        "_pk_id.100001.3ac3"

---
## 2.13 json
python object与json相互转化
常用功能：`json.loads` `json.dumps`

In [4]:
import json
url = 'https://api-web.lixiang.com/mall-api/v1-0/service-centers?types=RETAIL&types=DELIVER&types=AFTERSALE&types=SPRAY'
response = requests.get(url)
print(response.text[1:200])

"data":[{"id":"RBJS01","name":"理想汽车北京华熙LIVE零售中心","imgUrl":"https://p.ampmake.com/tur/rm/4085a4cd-44aa-41f7-9f88-5dabe9e99d65.jpg","openedAt":"2019年5月1日上午10:00","openingHours":"周一至周日10:00-22:00","addr


In [5]:
import json
obj = json.loads(response.text)
obj['data'][0]

{'id': 'RBJS01',
 'name': '理想汽车北京华熙LIVE零售中心',
 'imgUrl': 'https://p.ampmake.com/tur/rm/4085a4cd-44aa-41f7-9f88-5dabe9e99d65.jpg',
 'openedAt': '2019年5月1日上午10:00',
 'openingHours': '周一至周日10:00-22:00',
 'address': '北京市海淀区复兴路69号华熙LIVE·五棵松HI-UP B101、102商铺',
 'telephone': '010-86488161',
 'type': 'RETAIL',
 'status': 'INBUSINESS',
 'lng': 116.283715,
 'lat': 39.915205,
 'cityId': 110100,
 'cityName': '北京',
 'provinceId': 110000,
 'provinceName': '北京',
 'locations': {'baiduLng': 116.283715,
  'baiduLat': 39.915205,
  'tencentLng': None,
  'tencentLat': None,
  'gdLng': 116.277297,
  'gdLat': 39.908863},
 'testDriveStatus': 1,
 'testDriveDesc': '',
 'distance': None,
 'companyName': '理想智造汽车销售服务（北京）有限公司',
 'activityStartedAt': None,
 'activityEndedAt': None,
 'countyName': '海淀',
 'countyId': 110108}

In [6]:
json.dumps(obj['data'][0])

'{"id": "RBJS01", "name": "\\u7406\\u60f3\\u6c7d\\u8f66\\u5317\\u4eac\\u534e\\u7199LIVE\\u96f6\\u552e\\u4e2d\\u5fc3", "imgUrl": "https://p.ampmake.com/tur/rm/4085a4cd-44aa-41f7-9f88-5dabe9e99d65.jpg", "openedAt": "2019\\u5e745\\u67081\\u65e5\\u4e0a\\u534810:00", "openingHours": "\\u5468\\u4e00\\u81f3\\u5468\\u65e510:00-22:00", "address": "\\u5317\\u4eac\\u5e02\\u6d77\\u6dc0\\u533a\\u590d\\u5174\\u8def69\\u53f7\\u534e\\u7199LIVE\\u00b7\\u4e94\\u68f5\\u677eHI-UP B101\\u3001102\\u5546\\u94fa", "telephone": "010-86488161", "type": "RETAIL", "status": "INBUSINESS", "lng": 116.283715, "lat": 39.915205, "cityId": 110100, "cityName": "\\u5317\\u4eac", "provinceId": 110000, "provinceName": "\\u5317\\u4eac", "locations": {"baiduLng": 116.283715, "baiduLat": 39.915205, "tencentLng": null, "tencentLat": null, "gdLng": 116.277297, "gdLat": 39.908863}, "testDriveStatus": 1, "testDriveDesc": "", "distance": null, "companyName": "\\u7406\\u60f3\\u667a\\u9020\\u6c7d\\u8f66\\u9500\\u552e\\u670d\\u52a1\\

In [7]:
# 还有一种处理方法是用pandas直接读取
import pandas as pd
obj = pd.read_json('https://www.geometryauto.com/api/nev/dealer/getdealers?seriesCode=ge11')
obj

Status                                               Data  Message
0       200  {'DealerName': '新疆华新汽车销售有限公司', 'Address': '新疆维...  经销商获取成功
1       200  {'DealerName': '伊犁展彦汽车销售服务有限公司', 'Address': '新...  经销商获取成功
2       200  {'DealerName': '喀什通工吉沃汽车销售服务有限公司', 'Address': ...  经销商获取成功
3       200  {'DealerName': '无锡国昌新能源汽车销售有限公司', 'Address': '...  经销商获取成功
4       200  {'DealerName': '宁波甬成优行新能源汽车销售服务有限公司', 'Address...  经销商获取成功
5       200  {'DealerName': '上海晋熙汽车销售服务有限公司', 'Address': '上...  经销商获取成功
6       200  {'DealerName': '宁波帝豪汽车销售服务有限公司', 'Address': '浙...  经销商获取成功
7       200  {'DealerName': '大连福斯达几何汽车销售服务有限公司', 'Address':...  经销商获取成功
8       200  {'DealerName': '上海明友泓浩汽车销售有限公司', 'Address': '上...  经销商获取成功
9       200  {'DealerName': '上海天麦汽车销售服务有限公司', 'Address': '上...  经销商获取成功
10      200  {'DealerName': '台州吉悦电动汽车销售服务有限公司', 'Address': ...  经销商获取成功
11      200  {'DealerName': '上海浦之利汽车有限公司', 'Address': '上海市普...  经销商获取成功
12      200  {'DealerName': '上海华庭汽车销售服务有限公司', 'Address': '上...  经销商获取成功
13      200  {'DealerName': '上海吉庆新能源汽车销售有限公司', 'Address': '...  经销商获取成功
14      200  {'DealerName': '温州绿能银盾汽车销售有限公司', 'Address': '浙...  经销商获取成功
15      200  {'DealerName': '苏州瑞高汽车服务有限公司', 'Address': '江苏省...  经销商获取成功
16      200  {'DealerName': '南通奥易隆汽车销售服务有限公司', 'Address': '...  经销商获取成功
17      200  {'DealerName': '温州吉新汽车销售服务有限公司', 'Address': '浙...  经销商获取成功
18      200  {'DealerName': '瑞安吉瑞汽车服务有限公司', 'Address': '浙江省...  经销商获取成功
19      200  {'DealerName': '温州华云汽车销售服务有限公司', 'Address': '浙...  经销商获取成功
20      200  {'DealerName': '绍兴豪庭汽车销售服务有限公司　', 'Address': '...  经销商获取成功
21      200  {'DealerName': '苏州市天丰汇汽车销售服务有限公司', 'Address': ...  经销商获取成功
22      200  {'DealerName': '绍兴德能汽车销售服务有限公司', 'Address': '浙...  经销商获取成功
23      200  {'DealerName': '桐乡市嘉伦汽车销售服务有限公司', 'Address': '...  经销商获取成功
24      200  {'DealerName': '绍兴君驰汽车销售服务有限公司', 'Address': '浙...  经销商获取成功
25      200  {'DealerName': '青岛康利捷汽车销售服务有限责任公司', 'Address':...  经销商获取成功
26      200  {'DealerName': '浙江滨之利汽车有限公司', 'Address': '浙江省杭...  经销商获取成功
27      200  {'DealerName': '湖州市利驰汽车销售服务有限公司', 'Address': '...  经销商获取成功
28      200  {'DealerName': '杭州骏业汽车销售有限公司', 'Address': '浙江省...  经销商获取成功
29      200  {'DealerName': '泰州杰信新能源科技有限公司', 'Address': '江苏...  经销商获取成功
..      ...                                                ...      ...
123     200  {'DealerName': '海南青胜蓝汽车销售服务有限公司', 'Address': '...  经销商获取成功
124     200  {'DealerName': '海南蔚蓝汽车管理有限公司', 'Address': '海南省...  经销商获取成功
125     200  {'DealerName': '玉林市先行新能源汽车销售有限公司', 'Address': ...  经销商获取成功
126     200  {'DealerName': '鄂尔多斯市福华汽车销售服务有限公司', 'Address':...  经销商获取成功
127     200  {'DealerName': '海南和骏汽车销售有限公司', 'Address': '海南省...  经销商获取成功
128     200  {'DealerName': '贵州宏吉瑞新能源汽车销售服务有限公司', 'Address'...  经销商获取成功
129     200  {'DealerName': '陕西新丰泰新能源汽车销售服务有限公司', 'Address'...  经销商获取成功
130     200  {'DealerName': '陕西龙起汽车贸易有限公司', 'Address': '陕西省...  经销商获取成功
131     200  {'DealerName': '陕西益新源新能源汽车有限公司', 'Address': '陕...  经销商获取成功
132     200  {'DealerName': '西安国利汽车服务有限公司', 'Address': '陕西省...  经销商获取成功
133     200  {'DealerName': '陕西时代明珠汽车销售有限公司', 'Address': '陕...  经销商获取成功
134     200  {'DealerName': '重庆佳运恒星汽车销售有限公司', 'Address': '重...  经销商获取成功
135     200  {'DealerName': '广西吉开汽车销售服务有限公司', 'Address': '广...  经销商获取成功
136     200  {'DealerName': '贵州祥隆汽车销售服务有限责任公司', 'Address': ...  经销商获取成功
137     200  {'DealerName': '宝鸡市新星海新能源科技有限公司', 'Address': '...  经销商获取成功
138     200  {'DealerName': '贵州海翔汽车贸易服务有限公司', 'Address': '贵...  经销商获取成功
139     200  {'DealerName': '广安合鑫汽车销售有限公司', 'Address': '四川省...  经销商获取成功
140     200  {'DealerName': '博卡联（重庆）汽车销售服务有限公司', 'Address':...  经销商获取成功
141     200  {'DealerName': '重庆古甫新能源汽车有限公司', 'Address': '重庆...  经销商获取成功
142     200  {'DealerName': '黔西南州鑫吉新能源汽车销售有限公司', 'Address':...  经销商获取成功
143     200  {'DealerName': '中国第二重型机械集团德阳万路运业有限公司', 'Addres...  经销商获取成功
144     200  {'DealerName': '四川金信吉新汽车销售有限公司', 'Address': '四...  经销商获取成功
145     200  {'DealerName': '成都吉圣汽车销售有限公司', 'Address': '四川省...  经销商获取成功
146     200  {'DealerName': '成都西物汽车有限公司', 'Ad

---
## 2.14 hashlib
python object与json相互转化
常用功能：`json.loads` `json.dumps`

In [47]:


import hashlib
m=hashlib.md5()                               #括号内也可以传值，类型也要求是bytes类型
m.update('你好呀！'.encode('utf-8'))
print(m.hexdigest())                          #9e49eb8e75b9a87424e388b862ea5f83

# 与上述hash的结果一样

m=hashlib.md5('你'.encode('utf-8'))          #括号内也可以传值，类型也要求是bytes类型
m.update('好呀！'.encode('utf-8'))
print(m.hexdigest())   

9e49eb8e75b9a87424e388b862ea5f83
9e49eb8e75b9a87424e388b862ea5f83


---

## 2.15 hmac

hmac 提供带key的sha加密方式


In [2]:
import hmac
message = b'123'
key = b'123'
h = hmac.new(key, message, digestmod='MD5')
# 如果消息很长，可以多次调用h.update(msg)
h.hexdigest()


'b2a1ec0f3e0607099d7f39791c04e9a4'

---
## 2.16 bs4
beautiful soup 提供更高阶的html解析工具，方便使用xpath/xML/css selector的html解析

In [8]:
import requests
from bs4 import BeautifulSoup
headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
        "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7",
        "Cache-Control": "max-age=0",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
    }



doc = requests.get("https://book.douban.com/",headers=headers)
soup=BeautifulSoup(doc.text,'html.parser')

In [85]:
output = []
for obj in soup.select('div.author'):
    output.append(re.sub(r'\s','',obj.getText()))
    
print(output)
# soup.select('div.author')[0].getText()

['[日]冈岛二人', '罗翔', '[英]安娜·伯恩斯', '[挪威]托尔·海尔达尔', '甘耀明', '[英]哈里·科林斯', '[澳大利亚]格里高利·大卫·罗伯兹', '[美]菲利普·古雷维奇（PhilipGourevitch)', '西西', '[美]吴以义', '[英]露丝·韦尔', '[美]兰迪·胡特尔·爱泼斯坦', '【加】乔安娜·古德曼', '[俄]列夫·马诺维奇', '[美]科马克·麦卡锡', '[瑞士]汉斯·乌尔里希·奥布里斯特', '〔法〕让-克劳德·穆勒瓦', '[英]保罗·法兰奇', '[美]斯蒂芬·金', '[美]大卫·塞达里斯', '[美]安妮·普鲁', '田丰/林凯玄', '[英]斯蒂芬·弗莱（StephenFry）', '王明珂', '[智利]玛丽亚·路易莎·邦巴尔', '[美]罗友枝', '[法]埃尔韦·里谢编/[法]艾菲克斯绘', '[美]珍妮斯·A.拉德威', '赖香吟', '[英]亚当•尼科尔森著；[英]凯特•博克瑟绘', '[英]A·S·拜厄特', '左丘萌/末春', '[日]叶真中显', '[美]詹姆斯·纳雷摩尔', '淡豹', '[美]香奈儿·米勒', '[美]托马斯·品钦', '[美]安德烈娅·欧文/AndreaOwen', '[爱尔兰]席亚拉•格拉蒂', '[美]布赖恩·费根（BrianFagan）', '歪歪兔关键期早教项目组编绘', '[美]塔拉·韦斯特弗', '大J/卢俊', '太宰治', '麦家', '乔安娜柯尔著/布鲁斯迪根图', '张嘉佳', '[英]威廉·萨默塞特·毛姆', '阿兰德·丹姆文/亚历克斯·沃尔弗图', '山下英子']


In [94]:
output = []
#print(dir(soup.select('div.author')[0]))
#print(soup.select('div.cover a'))
for obj in soup.select('div.cover a'):
    output.append(obj['href'])
    
print(output)
# soup.select('div.author')[0].getText()

['https://book.douban.com/subject/34998166/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35154591/?icn=index-latestbook-subject', 'https://book.douban.com/subject/34926039/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35006761/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35080704/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35073029/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35093979/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35023969/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35085896/?icn=index-latestbook-subject', 'https://book.douban.com/subject/34912095/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35067595/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35069819/?icn=index-latestbook-subject', 'https://book.douban.com/subject/35090798/?icn=index-latestbook-subject', 'https://book.douban.com/subject/3509

---
## 2.17 selenium
selenium

In [1]:
from selenium import webdriver

In [2]:
driver = webdriver.PhantomJS()
driver.get('http://wm-motor.com')
driver.save_screenshot('123.png')

/usr/local/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '


True

---
## 2.18 webbrowser



In [53]:
import webbrowser
webbrowser.open("http://baidu.com")

False

---
## 2.19 http.server

构建局域网环境/本地服务器 2中为`simpleHTTPServer` 3中为`http.server`

In [54]:
import http.server
import socketserver
import webbrowser
import os

os.chdir('./wm-order-screen')
PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler
webbrowser.open("http://localhost:8000/prscreen/officialM3/aggregation.html")

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()


FileNotFoundError: [Errno 2] No such file or directory: './wm-order-screen'

---
## 2.20 numpy

1. 基础构造
2. 切片索引与操作
3. 函数
4. 矩阵代数

### 基础构造

In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[2,1],[2,2]])
print(a)
print(b)

print('-----------------')
print(np.empty([2,3]))
print(np.zeros([2,3]))
print(np.ones([2,3]))
print(np.asarray([1,2,3]))


print('-----------------')
print(np.arange(5))
print(np.arange(1,19,2))

[1 2 3]
[[2 1]
 [2 2]]
-----------------
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]
-----------------
[0 1 2 3 4]
[ 1  3  5  7  9 11 13 15 17]


In [7]:
print(a.ndim,a.shape,a.size,a.dtype)
print(b.ndim,b.shape,b.size,b.dtype)

1 (3,) 3 int64
2 (2, 2) 4 int64


### 切片索引与操作

In [17]:
a = np.arange(20)
print(a[1:4])

[1 2 3]


In [18]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])   # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [20]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
#(0,0) (1,1) (2,0)
print (y)

[1 4 5]


In [32]:
a = np.arange(9).reshape(3,3) 
print(a)

print (np.append(a, [[7,8,9]]))
print (np.append(a, [[7,8,9]], axis =0))
print (np.append(a, [[7,8,9],[7,8,9],[7,8,9]], axis =1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [7 8 9]]
[[0 1 2 7 8 9]
 [3 4 5 7 8 9]
 [6 7 8 7 8 9]]


### 函数

In [40]:
# np.sin, np.cos, np.tan
# np.around()
# add()，subtract()，multiply() 和 divide()
# amin(array,1) amax(array,1)
# 均值
print(np.mean(np.arange(5)))
# 加权平均
print(np.average(np.arange(5),weights =np.arange(5)) )
print(np.std(np.arange(5)))
print(np.var(np.arange(5)))

2.0
3.0
1.4142135623730951
2.0


In [42]:
a = np.array([[3,7],[9,1]])  
print(a)
print(np.sort(a))

[[3 7]
 [9 1]]
[[3 7]
 [1 9]]


### 矩阵代数

In [49]:
print(a)
print(a.T)
print(np.linalg.inv(a))

print(np.matmul(a,a))

[[3 7]
 [9 1]]
[[3 9]
 [7 1]]
[[-0.01666667  0.11666667]
 [ 0.15       -0.05      ]]
[[72 28]
 [36 64]]
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [52]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

np.matmul(ainv,b)

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]


array([[ 5.],
       [ 3.],
       [-2.]])

---
## 2.2X 

一些知道但不想用的模块

- 类似requests（所以可以不用）：
    - httplib
    - urllib
    - urllib2

- 爬虫框架（不如自己写）
    - scrapy
    - pyspider

- 无头浏览器
    - selenium